Model pACE_B6_N7_18_lic_lap_1.50, Test bulk_Si_diamond
Test run at 2020-08-19 12:58

model file: ../../models/pACE_B6_N7_18_lic_lap_1.50/model.py
============================================================
import os
from ase.calculators.lammpsrun import LAMMPS

os.environ["ASE_LAMMPSRUN_COMMAND"]="/Users/Cas/gits/lammps-ace/src/lmp_serial"

model_dir = os.path.dirname(os.path.realpath(__file__))

parameters = {'pair_style': 'pace',
              'pair_coeff': ['* * Si_B6_N7_18_lic_lap_1.5_rep_2B+ACE.ace Si']}

files = [os.path.join(model_dir, "Si_B6_N7_18_lic_lap_1.5_rep_2B+ACE.ace")]

calculator = LAMMPS(parameters=parameters, files=files)

no_checkpoint = True
============================================================
test file: /Users/Cas/gits/testing-framework/scripts/../tests/TiAl/bulk_Si_diamond/test.py
============================================================
Traceback (most recent call last):
  File "../../../scripts/run-model-test.py", line 114, in <module>
    sys.stdout.write(open(test_file).read())
FileNotFoundError: [Errno 2] No such file or directory: '/Users/Cas/gits/testing-framework/scripts/../tests/TiAl/bulk_Si_diamond/test.py'
